SELECT * FROM `ola_bookings_cleaned(sheet1)`;

#1. How many total booking were made in the  ola dataset
select count(*) as Total_Booking from `ola_bookings_cleaned(sheet1)`;

#2. what is the total revenue generated from all booking
select sum(Booking_value) as Total_revenue from `ola_bookings_cleaned(sheet1)`;

#3. what is the average customer rating received across all rides
select round(avg(Customer_Rating),2) as average_customer_ratings from `ola_bookings_cleaned(sheet1)`;

#4. what is the average Driver rating received across all rides
select round(avg(Driver_ratings),2) as average_driver_ratings from `ola_bookings_cleaned(sheet1)`;

#5. how many customer use ola service?
select count(distinct(Customer_ID)) as Customers from `ola_bookings_cleaned(sheet1)`;

#6.How much revenue was generated by each vehicle type?
select vehicle_type,sum(Booking_value) as Total_revenue from `ola_bookings_cleaned(sheet1)` group by Vehicle_Type order by Total_revenue DESC;

#7. How many bookings were made for each vehicle type?
select vehicle_type,count(*) as Total_booking from `ola_bookings_cleaned(sheet1)` group by Vehicle_Type order by Total_booking DESC;

#8. what is the average ride distance for each vehicle type?
select Vehicle_Type,avg(ride_distance) as average_ride_distance from `ola_bookings_cleaned(sheet1)` group by Vehicle_Type;

#9. what is the highest customer rating for each  vehicle_type?
select Vehicle_Type,max(Customer_Rating)  as highest_customer_ratings from `ola_bookings_cleaned(sheet1)` group by Vehicle_Type;

#10. how many rides were cancelled for each vehicle type?
select Vehicle_Type,count(*) as Total_Cancelled from `ola_bookings_cleaned(sheet1)` where Booking_Status<>'Success' group by Vehicle_Type;

#11. how much revenue was generated through each payment method?
select Payment_Method,sum(Booking_value) as Total_revenue from `ola_bookings_cleaned(sheet1)` group by Payment_Method;

#12. Which are the top 10 pickup locations generating the highest revenue?
select Pickup_Location ,sum(Booking_value) as highest_revenue from `ola_bookings_cleaned(sheet1)` group by Pickup_Location order by highest_revenue desc limit 10;

#13.Which are the top 10 drop locations generating the highest revenue?
select Drop_Location ,sum(Booking_value) as highest_revenue from `ola_bookings_cleaned(sheet1)` group by Drop_Location order by highest_revenue desc limit 10;

#14.compare the revenue contribution of different vehicle types?
select Vehicle_Type ,sum(Booking_value) as highest_revenue from `ola_bookings_cleaned(sheet1)` group by Vehicle_Type order by highest_revenue desc;

#15. what is daily revenue trend over time?
select i>>,sum(Booking_value)  as daily_revenue from `ola_bookings_cleaned(sheet1)` group by Time;

#16. how many bookings belong to each booking status?
select Booking_Status,count(*) as Total_Booking from `ola_bookings_cleaned(sheet1)` group by Booking_Status;

#17. How many rides were cancelled by customers?
select count(*) as Customer_Cancelled from `ola_bookings_cleaned(sheet1)` where Booking_Status='Canceled by Customer';

#18. How many rides were cancelled by Drivers?
select count(*) as Driver_Cancelled from `ola_bookings_cleaned(sheet1)` where Booking_Status='Canceled by Driver';

#19. which vehicle type has the highest number of cancelled rides?
select Vehicle_Type,count(*) as highest_number_of_cancel_rides from `ola_bookings_cleaned(sheet1)` where Booking_Status<>"Success" group by Vehicle_Type;

#20.what is overall cancellation rate of booking
select round(count(case when Booking_Status<>"Success" then 1 end) *100/count(*),2) as Cancellation_rate from `ola_bookings_cleaned(sheet1)`;

#21. what is the average customer rating for each vehicle type
select Vehicle_Type,round(avg(Customer_Rating),2) as Average_rating from `ola_bookings_cleaned(sheet1)` group by Vehicle_Type;

#22. what is the average driver rating for each vehicle type?
select Vehicle_Type,round(avg(Driver_Ratings),2) as Average_rating from `ola_bookings_cleaned(sheet1)` group by Vehicle_Type;

#23. which payment method is associated with the highest customer rating?
select Payment_Method,max(Customer_Rating) as Highest_customer_rating from `ola_bookings_cleaned(sheet1)` group by Payment_Method;

#24. which are the top 10 drop locations with the highest average customer ratings?
select Drop_Location,round(avg(Customer_Rating),2) as average_customer_ratings from `ola_bookings_cleaned(sheet1)` group by Drop_Location order by average_customer_ratings DESC limit 10;

#25. rank vehicle types based on the revenue they generate.
select Vehicle_Type,sum(Booking_value) as Total_revenue,
Rank() over(order by sum(Booking_value) DESC) as Revenue_Rank
from `ola_bookings_cleaned(sheet1)` group by Vehicle_Type;

#26. rank vehicle types based on the total number of rides.
select Vehicle_Type,count(*) as Total_rides,
dense_rank() over(order by count(*) DESC) as Ride_Rank
from `ola_bookings_cleaned(sheet1)` group by Vehicle_Type;

#27. how many successful rides were completed for each vehicle type?
select Vehicle_type,sum(case when Booking_Status="Success" then 1 else 0 end) as success_ride from `ola_bookings_cleaned(sheet1)` group by Vehicle_Type;

#28. what is the average booking value for each vehicle type?
select Vehicle_Type,avg(Booking_value) as Avg_booking_value from `ola_bookings_cleaned(sheet1)` group by Vehicle_Type;

#29. what is the highest booking value for each vehicle type?
select Vehicle_Type,max(Booking_value) as max_booking_value from `ola_bookings_cleaned(sheet1)` group by Vehicle_Type;

#30. rank vehicle types based on average customer ratings.
select Vehicle_Type,avg(Customer_Rating) as average_customer_ratings,
dense_rank() over(order by avg(Customer_Rating)  DESC) as Rating_rank
from `ola_bookings_cleaned(sheet1)`
group by Vehicle_Type;